export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ADDTOCART = 'ADDTOCART'
export const DELETEFROMCART = 'DELETEFROMCART'
export const SHOWALERT = 'SHOWALERT'
export const HIDEALERT = 'HIDEALERT'
export const CLEARCART = 'CLEARCART'